contacts-admin:
  - parent
travel-advice-publisher:
  # This is  a temporary workaround for the fact that 'parent' links
  # can sometimes be blobs of JSON (containing a breadcrumb, for example)
  # rather than the array of content IDs content-tagger currently expects. We
  # need to either improve the editing interface in content tagger to somehow
  # support this or wait until the publishing API no longer allows writing of
  # arbitrary JSON to the parent link.
  - parent
