contacts:
  - parent

travel-advice-publisher:
  # This is  a temporary workaround for the fact that 'parent' links
  # can sometimes be blobs of JSON (containing a breadcrumb, for example)
  # rather than the array of content IDs content-tagger currently expects. We
  # need to either improve the editing interface in content tagger to somehow
  # support this or wait until the publishing API no longer allows writing of
  # arbitrary JSON to the parent link.
  - parent

whitehall:
  # The 'parent' for a Whitehall edition (Editions being the only Whitehall
  # document type we are expecting to tag in content-tagger) is always a
  # topic (referred to as the 'primary specialist sector' in Whitehall).
  # Temporarily blacklisting this field for now until content-tagger supports
  # tagging topics in the parent field.
  - parent
