default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5

development:
  <<: *default
  database: content_tagger_development

test:
  <<: *default
  database: content_tagger_test

# In production the `DATABASE_URL` environment variable is automatically used.
