default: &default
  metrics:
    - name: Maximum Taxon Depth
      class: MaximumDepthMetric
      arguments:
        maximum_depth: 5
    - name: Maximum number of content item tagged to a taxon
      class: ContentCountMetric
      arguments:
        maximum: 100

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
