# Below is the list of distinct `publishing_app`s in the content-store, with
# the app that is (mostly) responsible for tagging its content.
#
# Leave an app empty to disable tagging for it.
#
a-migrated-app: content-tagger # for testing puposes
businesssupportfinder: content-tagger
calculators: content-tagger
calendars: content-tagger
collections-publisher: content-tagger
contacts: content-tagger
design-principles:
email-campaign-frontend:
external-link-tracker:
feedback:
frontend:
govuk_content_api:
hmrc-manuals-api: content-tagger
info-frontend:
licencefinder: content-tagger
manuals-frontend:
performanceplatform-big-screen-view:
policy-publisher: content-tagger
publisher: publisher
rummager:
service-manual-publisher:
short-url-manager:
smartanswers: content-tagger
specialist-publisher: specialist-publisher
spotlight:
static:
tariff:
travel-advice-publisher: content-tagger
whitehall: whitehall
